name: Deploy to Azure
on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy_azure_resources:
    name: Deploy Azure resources
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.x"

      - name: Deploy Bicep file
        id: deploy_bicep_file
        shell: bash
        run: |
          set -euo pipefail

          DEPLOYMENT_STACK_NAME="trigger-function-from-files"

          echo "Creating deployment stack..."
          az stack sub create \
            --action-on-unmanage "DeleteAll" \
            --deny-settings-mode none \
            --location "eastus" \
            --name "$DEPLOYMENT_STACK_NAME" \
            --template-file "${{ github.workspace }}/bicep/main.bicep" \
            --yes

          # Pass deployment stack name to output
          echo "DEPLOYMENT_STACK_NAME=$DEPLOYMENT_STACK_NAME" >> $GITHUB_OUTPUT

      - name: Publish function app
        run: |
          set -euo pipefail

          echo "Publishing code..."
          OUTPUT_FOLDER="${{ runner.temp }}/functionappoutput"
          PROJECT_PATH="${{ github.workspace }}/functionapp/functionapp.csproj"
          dotnet publish "$PROJECT_PATH" \
            --configuration Release \
            --output "$OUTPUT_FOLDER"

          echo "Copying host.json to output..."
          cp "${{ github.workspace }}/functionapp/host.json" "$OUTPUT_FOLDER"

          cd "$OUTPUT_FOLDER"
          dir

          echo "Zipping output folder..."
          ZIP_FILE_PATH="${{ runner.temp }}/functionapp.zip"
          zip -r "$ZIP_FILE_PATH" "$OUTPUT_FOLDER"

          echo "Deploying function app..."
          # DEPLOYMENT_STACK_NAME="${{ steps.deploy_bicep_file.outputs.DEPLOYMENT_STACK_NAME }}"
          DEPLOYMENT_STACK_NAME="trigger-function-from-files"
          DEPLOYMENT_STACK=$(az stack sub show -n "$DEPLOYMENT_STACK_NAME")
          RESOURCE_GROUP_NAME=$(echo "$DEPLOYMENT_STACK" | jq -r '.outputs.resourceGroupName.value')
          FUNCTION_APP_NAME=$(echo "$DEPLOYMENT_STACK" | jq -r '.outputs.functionAppName.value')
          az functionapp deployment source config-zip \
            --name "$FUNCTION_APP_NAME" \
            --resource-group "$(echo "$DEPLOYMENT_STACK" | jq -r '.outputs.resourceGroupName.value')" \
            --src "$ZIP_FILE_PATH"
